# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
pages:
  stage: deploy
  script:
    - echo -e "1c1\n< youtubeKey=\"AIzaSyBW1cZ-ehzqJ0PhClmNQFEu9RoDuqRQoD8\";\n---\n> youtubeKey=\"AIzaSyDM4gXM9reVQCOj18XQ2wEh_eIgK7leL3E\";\n"'|patch script.js -
    - mkdir .public
    - cp -r * .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master
